app/main/models.py
from datetime import datetime
from app.database import db
from app.search.search import add_to_index, remove_from_index, query_index


class SearchableMixin(object):
    @classmethod
    def search(cls, expression, page, per_page):
        ids, total = query_index(cls.__tablename__, expression, page, per_page)
        if total == 0:
            return cls.query.filter_by(id=0), 0
        when = []
        for i in range(len(ids)):
            when.append((ids[i], i))
        return cls.query.filter(cls.id.in_(ids)).order_by(
            db.case(when, value=cls.id)), total

    @classmethod
    def before_commit(cls, session):
        session._changes = {
            'add': list(session.new),
            'update': list(session.dirty),
            'delete': list(session.deleted)
        }

    @classmethod
    def after_commit(cls, session):
        for obj in session._changes['add']:
            if isinstance(obj, SearchableMixin):
                add_to_index(obj.__tablename__, obj)
        for obj in session._changes['update']:
            if isinstance(obj, SearchableMixin):
                add_to_index(obj.__tablename__, obj)
        for obj in session._changes['delete']:
            if isinstance(obj, SearchableMixin):
                remove_from_index(obj.__tablename__, obj)
        session._changes = None

    @classmethod
    def reindex(cls):
        for obj in cls.query:
            add_to_index(cls.__tablename__, obj)


db.event.listen(db.session, 'before_commit', SearchableMixin.before_commit)
db.event.listen(db.session, 'after_commit', SearchableMixin.after_commit)


class Post(SearchableMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    __searchable__ = ['body']

    def __repr__(self):
        return '<Post {}>'.format(self.body)

app/main/forms.py
from flask_wtf import FlaskForm
from flask import request
from wtforms import StringField, SubmitField
from wtforms import TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length
from app.auth.models import User


class EditProfileForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    about_me = TextAreaField('About me', validators=[Length(min=0, max=140)])
    submit = SubmitField('Submit')

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')


class PostForm(FlaskForm):
    post = TextAreaField('Say something', validators=[
        DataRequired(), Length(min=1, max=140)])
    submit = SubmitField('Submit')


class SearchForm(FlaskForm):
    q = StringField(validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

app/main/controllers.py
from flask import current_app
from flask import g
from datetime import datetime
from flask import Blueprint
from app.database import db
from flask_login import current_user, login_required
from flask import render_template, flash, redirect, url_for, request
from .forms import PostForm, EditProfileForm, SearchForm
from .models import Post
from app.auth.models import User

module = Blueprint('main', __name__)


@module.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()


@module.route('/', methods=['GET', 'POST'])
@module.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.post.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post is now live!')
        return redirect(url_for('main.index'))
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('main/index.html', title='Home',
                           form=form, posts=posts.items,
                           next_url=next_url,
                           prev_url=prev_url)


@module.route('/user/<id>')
@login_required
def user(id):
    user = User.query.filter_by(id=id).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.user', id=user.id, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.user', id=user.id, page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('main/user.html', user=user, posts=posts.items,
                           next_url=next_url, prev_url=prev_url)


@module.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.')
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('main/edit_profile.html', title='Edit Profile',
                           form=form)


@module.route('/explore')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, current_app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('main.explore', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.explore', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('main/index.html', title='Explore',
                           posts=posts.items,
                           next_url=next_url, prev_url=prev_url)


@module.route('/follow/<id>')
@login_required
def follow(id):
    user = User.query.filter_by(id=id).first()
    if user is None:
        flash('User with id {} not found.'.format(id))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('main.user', id=id))
    current_user.follow(user)
    db.session.commit()
    flash('You are following {}!'.format(user.username))
    return redirect(url_for('main.user', id=id))


@module.route('/unfollow/<id>')
@login_required
def unfollow(id):
    user = User.query.filter_by(id=id).first()
    if user is None:
        flash('User with id {} not found.'.format(id))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash('You cannot unfollow yourself!')
        return redirect(url_for('main.user', id=id))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following {}.'.format(user.username))
    return redirect(url_for('main.user', id=id))


@module.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.explore'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])
    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('main/search.html', title='Search', posts=posts,
                           next_url=next_url, prev_url=prev_url)


@module.errorhandler(404)
def not_found_error(error):
    return render_template('errors/404.html'), 404


@module.errorhandler(500)
def internal_error(error):
    db.session.rollback()
    return render_template('errors/500.html'), 500

app/templates/main/_post.html
<table class="table table-hover">
    <tr>
        <td width="70px">
            <a href="{{ url_for('main.user', id=post.author.id) }}">
                <img src="{{ post.author.avatar(70) }}" />
            </a>
        </td>
        <td>
            <a href="{{ url_for('main.user', id=post.author.id) }}">
                {{ post.author.username }}
            </a>
            said {{ moment(post.timestamp).fromNow() }}:<br>
            {{ post.body }}
        </td>
    </tr>
</table>

app/templates/main/base.html
{% from 'bootstrap/form.html' import render_form, render_field %}
<!doctype html>
<html lang="en">
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block styles %}
        <!-- Bootstrap CSS -->
        {{ bootstrap.load_css() }}
        {% endblock %}

        <title>
            {% if title %}
                {{ title }} - Miniblog
            {% else %}
                Welcome to Miniblog
            {% endif %}
        </title>
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-primary mb-2">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('main.index') }}"> Miniblog</a>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.explore') }}">Explore</a>
                    </li>
                    {% if current_user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.user', id=current_user.id) }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                    {% if g.search_form %}
                    <li class="nav-item">
                        <form method="get" action="{{ url_for('main.search') }}">
                            {{ render_field(g.search_form.q, form_type="inline", size=20, class='form-control', placeholder='Search') }}
                        </form>
                    </li>
                    {% endif %}
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-warning" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block app_content %}
            {% endblock %}
        </div>
        {% block scripts %}
            <!-- Optional JavaScript -->
            {{ bootstrap.load_js() }}
            {{ moment.include_moment() }}
        {% endblock %}
    </body>
</html>

app/templates/main/edit_profile.html
{% extends "main/base.html" %}
{% from 'bootstrap/form.html' import render_form, render_field %}

{% block app_content %}
<h1>Edit Profile</h1>
<div class="row">
    <div class="col-md-6">
        {{ render_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "main/base.html" %}
{% from 'bootstrap/form.html' import render_form, render_field %}

{% block app_content %}
<h1>Hello, {{ current_user.username }}</h1>
{% if form %}
<div class="row mb-3">
    <div class="col-md-6">
        {{ render_form(form) }}
    </div>
</div>
{% endif %}
{% for post in posts %}
    {% include 'main/_post.html' %}
{% endfor %}
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item{% if not prev_url %} disabled{% endif %}">
            <a class="page-link" href="{{ prev_url or '#' }}">
                <span aria-hidden="true">&larr;</span> Newer posts
            </a>
        </li>
        <li class="page-item{% if not next_url %} disabled{% endif %}">
            <a class="page-link" href="{{ next_url or '#' }}">
                Older posts <span aria-hidden="true">&rarr;</span>
            </a>
        </li>
    </ul>
</nav>

{% endblock %}

app/templates/main/search.html
{% extends "main/base.html" %}

{% block app_content %}

<h1>Search Results</h1>

{% for post in posts %}
    {% include 'main/_post.html' %}
{% endfor %}

<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item{% if not prev_url %} disabled{% endif %}">
            <a class="page-link" href="{{ prev_url or '#' }}">
                <span aria-hidden="true">&larr;</span> Previous results
            </a>
        </li>
        <li class="page-item{% if not next_url %} disabled{% endif %}">
            <a class="page-link" href="{{ next_url or '#' }}">
                Next results <span aria-hidden="true">&rarr;</span>
            </a>
        </li>
    </ul>
</nav>

{% endblock %}

app/templates/main/user.html
{% extends "main/base.html" %}

{% block app_content %}
<div class="row">
    <div class="col-md-2">
        <img src="{{ user.avatar(128) }}">
    </div>
    <div class="col-md-6">
        <h1>User: {{ user.username }}</h1>
        {% if user.about_me %}
        <p>{{ user.about_me }}</p>
        {% endif %}
        {% if user.last_seen %}
        <p>Last seen on: {{ moment(user.last_seen).format('LLL') }}</p>
        {% endif %}
        <p>
            {{ user.followers.count() }} followers, {{ user.followed.count() }} following.
        </p>
        {% if user == current_user %}
        <p><a href="{{ url_for('main.edit_profile') }}">Edit your profile</a></p>
        {% elif not current_user.is_following(user) %}
        <p>
            <a href="{{ url_for('main.follow', id=user.id) }}">Follow</a>
        </p>
        {% else %}
        <p>
            <a href="{{ url_for('main.unfollow', id=user.id) }}">Unfollow</a>
        </p>
        {% endif %}
    </div>
</div>
{% for post in posts %}
    {% include 'main/_post.html' %}
{% endfor %}
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item{% if not prev_url %} disabled{% endif %}">
            <a class="page-link" href="{{ prev_url or '#' }}">
                <span aria-hidden="true">&larr;</span> Newer posts
            </a>
        </li>
        <li class="page-item{% if not next_url %} disabled{% endif %}">
            <a class="page-link" href="{{ next_url or '#' }}">
                Older posts <span aria-hidden="true">&rarr;</span>
            </a>
        </li>
    </ul>
</nav>
{% endblock %}